development:
  adapter: postgresql
  encoding: unicode
  database: skyjam_development
  pool: 5
  username: ferdi
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: skyjam_test
  pool: 5
  username: ferdi
  password:

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL', '') %>
