name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 3.0.2
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0.2

    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run rubocop
      run: |
        bundle exec rubocop || true

    - name: Install node
      run: sudo apt-get install nodejs

    - name: Yarn install
      run: yarn --frozen-lockfile

    - name: Setup Database
      run: |
        cp config/database.yml.github-actions config/database.yml
        bundle exec rake db:create
        bundle exec rake db:schema:load
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

    - name: Run tests
      run: |
        bundle exec rake
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
